---
title: "GSE114530"
author: "Yifang Liu"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    code_folding: hide
    fig_width: 3.5
    fig_height: 3.5
    highlight: kate
    thumbnails: false
    lightbox: true
    gallery: true
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

options(max.print = 200)
opts_chunk$set(echo = TRUE,
               cache = FALSE,
               prompt = FALSE,
               tidy = TRUE,
               comment = NA,
               message = FALSE,
               warning = FALSE,
               dev = c("png", "pdf"),
               fig.width = 3.5,
               fig.height = 3.5,
               fig.align = "center",
               # fig.path = 'PDFs_/',
               dpi = 72)
opts_knit$set(width = 75)
```

# Update

2020-10-08:

  * GSE114530
  
```{r setup}
set.seed(123)
options(stringsAsFactors = FALSE)

suppressPackageStartupMessages({
  library(Matrix)
  library(tidyverse)
  library(Seurat)
  library(GEOquery)
})
```

```{r download_data}
raw_data <- "../raw_data/"
if (!dir.exists(raw_data)) {dir.create(raw_data)}

results <- "../results/"
if (!dir.exists(results)) {dir.create(results)}

GSE <- "GSE114530"
# geo <- getGEOSuppFiles(GSE, makeDirectory = FALSE, baseDir = raw_data)

Species <- "Human"
Tissue <- "Kidney"
```

```{bash}
# tar -C ../raw_data/ -xvf ../raw_data/GSE114530_RAW.tar
```


```{r wk09}
sample <- "wk09"
GSM <- "GSM3509837"
number <- 1

barcode_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_barcodes.tsv.gz")
features_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_genes.tsv.gz")
matrix_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_matrix.mtx.gz")

mat <- readMM(file = matrix_path)
feature_names <- read.delim(features_path, header = FALSE)
barcode_names <- read.delim(barcode_path, header = FALSE)

dim(mat)
mat[1:3, 1:3]
colnames(mat) <- barcode_names$V1
rownames(mat) <- feature_names$V1
mat[1:3, 1:3]

barcodes_celltypes <- read.csv(paste0("../raw_data/", sample, "_barcodes_celltypes.csv"))
str(barcodes_celltypes)

mat_wk09 <- mat[ , barcodes_celltypes$cell.barcode]

seuratObj_wk09 <- CreateSeuratObject(counts = mat_wk09)
seuratObj_wk09 <- NormalizeData(seuratObj_wk09)
seuratObj_wk09 <- FindVariableFeatures(seuratObj_wk09, selection.method = "vst", nfeatures = 2000)
all_genes <- rownames(seuratObj_wk09)
seuratObj_wk09 <- ScaleData(seuratObj_wk09, features = all_genes)

seuratObj_wk09$celltype_id <- as.factor(barcodes_celltypes$cell.type.knn)
Idents(seuratObj_wk09) <- "celltype_id"
clusterMetadataTable <- table(seuratObj_wk09@meta.data[ , "celltype_id"]) %>% as.data.frame()
colnames(clusterMetadataTable) <- c("celltype_id", "count")
print(clusterMetadataTable$celltype_id)

# export clusterMetadataTable
write.csv(clusterMetadataTable,
          file = paste0(results, "/", GSE, "_", sample, "_clusterMetadataTable", ".csv"),
          row.names = FALSE)

# extract data matrix from DotPlot function
dot <- DotPlot(object = seuratObj_wk09, features = all_genes)
gene2clusterTable <- dot$data
colnames(gene2clusterTable) <- c("avg_exp", "pct_exp", "gene", "celltype_id", "avg_exp_scaled")
# check max value
summary(gene2clusterTable$avg_exp)

# export gene2clusterTable
write.csv(gene2clusterTable,
          file = paste0(results, "/", GSE, "_", sample, "_gene2clusterTable", ".csv"),
          row.names = FALSE)

oneFile <- NULL
clusterMetadataTable <- subset(clusterMetadataTable, count >= 3)
for(celltype_id in clusterMetadataTable$celltype_id){
    markers <- FindMarkers(seuratObj_wk09, ident.1 = celltype_id, only.pos = TRUE)
    markers <- cbind(row.names(markers), markers)
    colnames(markers)[1] <- "gene"
    
    markers$celltype_id <- celltype_id
    markers <- markers[order(-markers$avg_logFC), ]
    markers <- subset(markers, p_val_adj < 0.05)
    markers <- head(markers, 100)
    
    oneFile <- rbind(oneFile, markers)
}

# export markersTable
write.csv(oneFile,
          file = paste0(results, "/", GSE, "_", sample, "_markersTable", ".csv"),
          row.names = FALSE)

```


```{r wk11}
sample <- "wk11"
GSM <- "GSM3509838"
number <- 2

barcode_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_barcodes.tsv.gz")
features_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_genes.tsv.gz")
matrix_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_matrix.mtx.gz")

mat <- readMM(file = matrix_path)
feature_names <- read.delim(features_path, header = FALSE)
barcode_names <- read.delim(barcode_path, header = FALSE)

dim(mat)
mat[1:3, 1:3]
colnames(mat) <- barcode_names$V1
rownames(mat) <- feature_names$V1
mat[1:3, 1:3]

barcodes_celltypes <- read.csv(paste0("../raw_data/", sample, "_barcodes_celltypes.csv"))
str(barcodes_celltypes)

mat_wk11 <- mat[ , barcodes_celltypes$cell.barcode]

seuratObj_wk11 <- CreateSeuratObject(counts = mat_wk11)
seuratObj_wk11 <- NormalizeData(seuratObj_wk11)
seuratObj_wk11 <- FindVariableFeatures(seuratObj_wk11, selection.method = "vst", nfeatures = 2000)
all_genes <- rownames(seuratObj_wk11)
seuratObj_wk11 <- ScaleData(seuratObj_wk11, features = all_genes)

seuratObj_wk11$celltype_id <- as.factor(barcodes_celltypes$cell.type.knn)
Idents(seuratObj_wk11) <- "celltype_id"
clusterMetadataTable <- table(seuratObj_wk11@meta.data[ , "celltype_id"]) %>% as.data.frame()
colnames(clusterMetadataTable) <- c("celltype_id", "count")
print(clusterMetadataTable$celltype_id)

# export clusterMetadataTable
write.csv(clusterMetadataTable,
          file = paste0(results, "/", GSE, "_", sample, "_clusterMetadataTable", ".csv"),
          row.names = FALSE)

# extract data matrix from DotPlot function
dot <- DotPlot(object = seuratObj_wk11, features = all_genes)
gene2clusterTable <- dot$data
colnames(gene2clusterTable) <- c("avg_exp", "pct_exp", "gene", "celltype_id", "avg_exp_scaled")
# check max value
summary(gene2clusterTable$avg_exp)

# export gene2clusterTable
write.csv(gene2clusterTable,
          file = paste0(results, "/", GSE, "_", sample, "_gene2clusterTable", ".csv"),
          row.names = FALSE)

oneFile <- NULL
clusterMetadataTable <- subset(clusterMetadataTable, count >= 3)
for(celltype_id in clusterMetadataTable$celltype_id){
    markers <- FindMarkers(seuratObj_wk11, ident.1 = celltype_id, only.pos = TRUE)
    markers <- cbind(row.names(markers), markers)
    colnames(markers)[1] <- "gene"
    
    markers$celltype_id <- celltype_id
    markers <- markers[order(-markers$avg_logFC), ]
    markers <- subset(markers, p_val_adj < 0.05)
    markers <- head(markers, 100)
    
    oneFile <- rbind(oneFile, markers)
}

# export markersTable
write.csv(oneFile,
          file = paste0(results, "/", GSE, "_", sample, "_markersTable", ".csv"),
          row.names = FALSE)

```


```{r wk13}
sample <- "wk13"
GSM <- "GSM3509839"
number <- 3

barcode_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_barcodes.tsv.gz")
features_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_genes.tsv.gz")
matrix_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_matrix.mtx.gz")

mat <- readMM(file = matrix_path)
feature_names <- read.delim(features_path, header = FALSE)
barcode_names <- read.delim(barcode_path, header = FALSE)

dim(mat)
mat[1:3, 1:3]
colnames(mat) <- barcode_names$V1
rownames(mat) <- feature_names$V1
mat[1:3, 1:3]

barcodes_celltypes <- read.csv(paste0("../raw_data/", sample, "_barcodes_celltypes.csv"))
str(barcodes_celltypes)

mat_wk13 <- mat[ , barcodes_celltypes$cell.barcode]

seuratObj_wk13 <- CreateSeuratObject(counts = mat_wk13)
seuratObj_wk13 <- NormalizeData(seuratObj_wk13)
seuratObj_wk13 <- FindVariableFeatures(seuratObj_wk13, selection.method = "vst", nfeatures = 2000)
all_genes <- rownames(seuratObj_wk13)
seuratObj_wk13 <- ScaleData(seuratObj_wk13, features = all_genes)

seuratObj_wk13$celltype_id <- as.factor(barcodes_celltypes$cell.type.knn)
Idents(seuratObj_wk13) <- "celltype_id"
clusterMetadataTable <- table(seuratObj_wk13@meta.data[ , "celltype_id"]) %>% as.data.frame()
colnames(clusterMetadataTable) <- c("celltype_id", "count")
print(clusterMetadataTable$celltype_id)

# export clusterMetadataTable
write.csv(clusterMetadataTable,
          file = paste0(results, "/", GSE, "_", sample, "_clusterMetadataTable", ".csv"),
          row.names = FALSE)

# extract data matrix from DotPlot function
dot <- DotPlot(object = seuratObj_wk13, features = all_genes)
gene2clusterTable <- dot$data
colnames(gene2clusterTable) <- c("avg_exp", "pct_exp", "gene", "celltype_id", "avg_exp_scaled")
# check max value
summary(gene2clusterTable$avg_exp)

# export gene2clusterTable
write.csv(gene2clusterTable,
          file = paste0(results, "/", GSE, "_", sample, "_gene2clusterTable", ".csv"),
          row.names = FALSE)

oneFile <- NULL
clusterMetadataTable <- subset(clusterMetadataTable, count >= 3)
for(celltype_id in clusterMetadataTable$celltype_id){
    markers <- FindMarkers(seuratObj_wk13, ident.1 = celltype_id, only.pos = TRUE)
    markers <- cbind(row.names(markers), markers)
    colnames(markers)[1] <- "gene"
    
    markers$celltype_id <- celltype_id
    markers <- markers[order(-markers$avg_logFC), ]
    markers <- subset(markers, p_val_adj < 0.05)
    markers <- head(markers, 100)
    
    oneFile <- rbind(oneFile, markers)
}

# export markersTable
write.csv(oneFile,
          file = paste0(results, "/", GSE, "_", sample, "_markersTable", ".csv"),
          row.names = FALSE)

```


```{r wk16}
sample <- "wk16"
GSM <- "GSM3143601"
number <- 4

barcode_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_barcodes.tsv.gz")
features_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_genes.tsv.gz")
matrix_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_matrix.mtx.gz")

mat <- readMM(file = matrix_path)
feature_names <- read.delim(features_path, header = FALSE)
barcode_names <- read.delim(barcode_path, header = FALSE)

dim(mat)
mat[1:3, 1:3]
colnames(mat) <- barcode_names$V1
rownames(mat) <- feature_names$V1
mat[1:3, 1:3]

barcodes_celltypes <- read.csv(paste0("../raw_data/", sample, "_barcodes_celltypes.csv"))
str(barcodes_celltypes)

# length(intersect(barcodes_celltypes$cell.barcode, colnames(mat)))

mat_wk16 <- mat[ , barcodes_celltypes$cell.barcode]
dim(mat_wk16)

seuratObj_wk16 <- CreateSeuratObject(counts = mat_wk16)
seuratObj_wk16 <- NormalizeData(seuratObj_wk16)
seuratObj_wk16 <- FindVariableFeatures(seuratObj_wk16, selection.method = "vst", nfeatures = 2000)
all_genes <- rownames(seuratObj_wk16)
seuratObj_wk16 <- ScaleData(seuratObj_wk16, features = all_genes)

seuratObj_wk16$celltype_id <- as.factor(barcodes_celltypes$cell.type.knn)
Idents(seuratObj_wk16) <- "celltype_id"
clusterMetadataTable <- table(seuratObj_wk16@meta.data[ , "celltype_id"]) %>% as.data.frame()
colnames(clusterMetadataTable) <- c("celltype_id", "count")
print(clusterMetadataTable$celltype_id)

# export clusterMetadataTable
write.csv(clusterMetadataTable,
          file = paste0(results, "/", GSE, "_", sample, "_clusterMetadataTable", ".csv"),
          row.names = FALSE)

# extract data matrix from DotPlot function
dot <- DotPlot(object = seuratObj_wk16, features = all_genes)
gene2clusterTable <- dot$data
colnames(gene2clusterTable) <- c("avg_exp", "pct_exp", "gene", "celltype_id", "avg_exp_scaled")
# check max value
summary(gene2clusterTable$avg_exp)

# export gene2clusterTable
write.csv(gene2clusterTable,
          file = paste0(results, "/", GSE, "_", sample, "_gene2clusterTable", ".csv"),
          row.names = FALSE)

oneFile <- NULL
clusterMetadataTable <- subset(clusterMetadataTable, count >= 3)
for(celltype_id in clusterMetadataTable$celltype_id){
    markers <- FindMarkers(seuratObj_wk16, ident.1 = celltype_id, only.pos = TRUE)
    markers <- cbind(row.names(markers), markers)
    colnames(markers)[1] <- "gene"
    
    markers$celltype_id <- celltype_id
    markers <- markers[order(-markers$avg_logFC), ]
    markers <- subset(markers, p_val_adj < 0.05)
    markers <- head(markers, 100)
    
    oneFile <- rbind(oneFile, markers)
}

# export markersTable
write.csv(oneFile,
          file = paste0(results, "/", GSE, "_", sample, "_markersTable", ".csv"),
          row.names = FALSE)

```


```{r wk18}
sample <- "wk18"
GSM <- "GSM3509840"
number <- 5

barcode_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_barcodes.tsv.gz")
features_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_genes.tsv.gz")
matrix_path <- paste0(raw_data, GSM, "_", number, "_", sample, "_matrix.mtx.gz")

mat <- readMM(file = matrix_path)
feature_names <- read.delim(features_path, header = FALSE)
barcode_names <- read.delim(barcode_path, header = FALSE)

dim(mat)
mat[1:3, 1:3]
colnames(mat) <- barcode_names$V1
rownames(mat) <- feature_names$V1
mat[1:3, 1:3]

barcodes_celltypes <- read.csv(paste0("../raw_data/", sample, "_barcodes_celltypes.csv"))
str(barcodes_celltypes)

mat_wk18 <- mat[ , barcodes_celltypes$cell.barcode]

seuratObj_wk18 <- CreateSeuratObject(counts = mat_wk18)
seuratObj_wk18 <- NormalizeData(seuratObj_wk18)
seuratObj_wk18 <- FindVariableFeatures(seuratObj_wk18, selection.method = "vst", nfeatures = 2000)
all_genes <- rownames(seuratObj_wk18)
seuratObj_wk18 <- ScaleData(seuratObj_wk18, features = all_genes)

seuratObj_wk18$celltype_id <- as.factor(barcodes_celltypes$cell.type.knn)
Idents(seuratObj_wk18) <- "celltype_id"
clusterMetadataTable <- table(seuratObj_wk18@meta.data[ , "celltype_id"]) %>% as.data.frame()
colnames(clusterMetadataTable) <- c("celltype_id", "count")
print(clusterMetadataTable$celltype_id)

# export clusterMetadataTable
write.csv(clusterMetadataTable,
          file = paste0(results, "/", GSE, "_", sample, "_clusterMetadataTable", ".csv"),
          row.names = FALSE)

# extract data matrix from DotPlot function
dot <- DotPlot(object = seuratObj_wk18, features = all_genes)
gene2clusterTable <- dot$data
colnames(gene2clusterTable) <- c("avg_exp", "pct_exp", "gene", "celltype_id", "avg_exp_scaled")
# check max value
summary(gene2clusterTable$avg_exp)

# export gene2clusterTable
write.csv(gene2clusterTable,
          file = paste0(results, "/", GSE, "_", sample, "_gene2clusterTable", ".csv"),
          row.names = FALSE)

oneFile <- NULL
clusterMetadataTable <- subset(clusterMetadataTable, count >= 3)
for(celltype_id in clusterMetadataTable$celltype_id){
    markers <- FindMarkers(seuratObj_wk18, ident.1 = celltype_id, only.pos = TRUE)
    markers <- cbind(row.names(markers), markers)
    colnames(markers)[1] <- "gene"
    
    markers$celltype_id <- celltype_id
    markers <- markers[order(-markers$avg_logFC), ]
    markers <- subset(markers, p_val_adj < 0.05)
    markers <- head(markers, 100)
    
    oneFile <- rbind(oneFile, markers)
}

# export markersTable
write.csv(oneFile,
          file = paste0(results, "/", GSE, "_", sample, "_markersTable", ".csv"),
          row.names = FALSE)

```


```{r Combine}
sample <- "Combine"

seuratObj <- merge(seuratObj_wk09, y = c(seuratObj_wk11, seuratObj_wk13, seuratObj_wk16, seuratObj_wk18), add.cell.ids = c("wk09", "wk11", "wk13", "wk16", "wk18"))

rm(seuratObj_wk09, seuratObj_wk11, seuratObj_wk13, seuratObj_wk16, seuratObj_wk18)

seuratObj <- NormalizeData(seuratObj)
seuratObj <- FindVariableFeatures(seuratObj, selection.method = "vst", nfeatures = 2000)
all_genes <- rownames(seuratObj)
seuratObj <- ScaleData(seuratObj, features = all_genes)

# metadata <- seuratObj@meta.data
Idents(seuratObj) <- "celltype_id"

clusterMetadataTable <- table(seuratObj@meta.data[ , "celltype_id"]) %>% as.data.frame()
colnames(clusterMetadataTable) <- c("celltype_id", "count")
print(clusterMetadataTable$celltype_id)

# export clusterMetadataTable
write.csv(clusterMetadataTable,
          file = paste0(results, "/", GSE, "_", sample, "_clusterMetadataTable", ".csv"),
          row.names = FALSE)

# extract data matrix from DotPlot function
dot <- DotPlot(object = seuratObj, features = all_genes)
gene2clusterTable <- dot$data
colnames(gene2clusterTable) <- c("avg_exp", "pct_exp", "gene", "celltype_id", "avg_exp_scaled")
# check max value
summary(gene2clusterTable$avg_exp)

# export gene2clusterTable
write.csv(gene2clusterTable,
          file = paste0(results, "/", GSE, "_", sample, "_gene2clusterTable", ".csv"),
          row.names = FALSE)

oneFile <- NULL
clusterMetadataTable <- subset(clusterMetadataTable, count >= 3)
for(celltype_id in clusterMetadataTable$celltype_id){
    markers <- FindMarkers(seuratObj, ident.1 = celltype_id, only.pos = TRUE)
    markers <- cbind(row.names(markers), markers)
    colnames(markers)[1] <- "gene"
    
    markers$celltype_id <- celltype_id
    markers <- markers[order(-markers$avg_logFC), ]
    markers <- subset(markers, p_val_adj < 0.05)
    markers <- head(markers, 100)
    
    oneFile <- rbind(oneFile, markers)
}

# export markersTable
write.csv(oneFile,
          file = paste0(results, "/", GSE, "_", sample, "_markersTable", ".csv"),
          row.names = FALSE)

```


# Notes

2020-06-01:

  * Process GSE131971 LL3 high resolution.

2020-04-23:

  * Update output file name from Matrix to gene2clusterTable; Add one more output file clusterMetadataTable.

2020-04-19:

  * Process GSE133486 DropSeqSVF.

# Session Info

```{r sessioninfo, message=TRUE}
sessionInfo()
```

